dist: xenial
language: python
python:
  - 3.7
install:
  - pip install -r dev_requirements.txt
  - pip install coveralls
script:
  - coverage run --source=nickelodeon manage.py test
after_success:
  coveralls
