language: python
python:
  - 3.5
before_install:
  - sudo apt-get update
  - sudo apt-get -y install ffmpeg
install:
  - pip install -r dev_requirements.txt
  - pip install coveralls
script:
  - coverage run --source=nickelodeon manage.py test
after_success:
  coveralls
