version: '2'  
services:
  minio:
    image: minio/minio:latest
    volumes:
      - ../media:/data
    expose:
      - "9000"
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
  nginx:
    image: nginx:latest
    container_name: ny01
    ports:
      - "8000:8000"
      - "4443:4443"
    volumes:
      - ../:/app/
      - ../nginx:/etc/nginx/conf.d
    depends_on:
      - web
    links:
      - minio
  web:
    stop_signal: SIGINT
    build:
      context: ..
      dockerfile: docker/django.dockerfile
    container_name: dy01
    volumes:
      - ../:/app/:rw
    expose:
      - "8000"
    user: ${USERID}:${GROUPID}
    links:
      - redis
      - minio
  redis:
    image: redis:latest
    container_name: ry01
    ports:
      - "6379:6379"