version: '2'  
services:
  nginx:
    image: nginx:latest
    container_name: ny01
    ports:
      - "8000:8000"
    volumes:
      - ../:/app/
      - ../nginx:/etc/nginx/conf.d
    depends_on:
      - web
  web:
    stop_signal: SIGINT
    build:
      context: ..
      dockerfile: docker/django.dockerfile
    container_name: dy01
    volumes:
      - ../:/app/:rw
    expose:
      - "8000"
    user: ${USERID}:${GROUPID}
    links:
      - redis
  redis:
    image: redis:latest
    container_name: ry01
    ports:
      - "6379:6379"